apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: staging 
  name: developer 
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: staging 
  name: admin 
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]